apiVersion: apps/v1
kind: Deployment
metadata:
  name: millionui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: millionui
  template:
    metadata:
      labels:
        app: millionui
    spec:
      containers:
        - name: consumerportal
          image: microcert.azurecr.io/millionuiqa:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret