apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumerportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumerportal
  template:
    metadata:
      labels:
        app: consumerportal
    spec:
      containers:
        - name: consumerportal
          image: microcert.azurecr.io/consumerportal:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret